//! USD (Universal Scene Description), formato de Pixar.
//!
//! Exporta mallas como geometría estática en `.usda` (formato de texto ASCII).
//! **Sin composición:** capas, variantes, referencias y payloads quedan
//! explícitamente fuera de este módulo. Es una frontera clara que impide que
//! este exportador acabe capturando todo el modelo de composición de USD, que
//! es complejo y fuera del alcance de interoperabilidad de mallas.
//!
//! # Ventaja de USD sobre glTF
//!
//! USD permite `upAxis = "Z"` en el stage, así que **no requiere conversión de
//! ejes**. Eso simplifica la exportación, mantiene la precisión exacta de los
//! números, y es un argumento para preferir USD en flujos de CAD. glTF no ofrece
//! esa opción: su especificación exige Y arriba, punto.

use std::fmt::Write as _;
use std::path::Path;

use crate::{InteropError, Result, TriangleSoup};

/// Escribe una malla como geometría estática USD en `.usda`.
///
/// - `upAxis = "Z"`: FORGE nativo, sin conversión.
/// - `metersPerUnit = 0.001`: los datos internos están en milímetros.
/// - `UsdGeomMesh`: points, faceVertexCounts, faceVertexIndices, normals.
pub fn write_usda(path: impl AsRef<Path>, soup: &TriangleSoup) -> Result<()> {
    let path = path.as_ref();
    let content = to_string(soup)?;
    std::fs::write(path, content).map_err(|e| InteropError::Io {
        path: path.into(),
        source: e,
    })
}

/// Genera el contenido USDA como string.
pub fn to_string(soup: &TriangleSoup) -> Result<String> {
    soup.validate()?;

    let mut s = String::with_capacity(soup.positions.len() * 48);

    // Header
    writeln!(s, "#usda 1.0").ok();
    writeln!(s, "(\n").ok();
    writeln!(s, "    doc = \"Generated by FORGE\"").ok();
    writeln!(s, "    upAxis = \"Z\"").ok();
    writeln!(s, "    metersPerUnit = 0.001").ok();
    writeln!(s, ")").ok();
    writeln!(s).ok();

    let nombre = if soup.name.is_empty() {
        "malla"
    } else {
        &soup.name
    };

    // Stage scope
    writeln!(s, "def Xform \"stage\"").ok();
    writeln!(s, "{{").ok();
    writeln!(s, "    def Mesh \"{}\"", nombre).ok();
    writeln!(s, "    {{").ok();

    // Points: 3 componentes por vértice
    writeln!(s, "        point3f[] points = [").ok();
    for (i, p) in soup.positions.iter().enumerate() {
        if i % 3 == 0 && i > 0 {
            writeln!(s).ok();
        } else if i > 0 {
            write!(s, ", ").ok();
        }
        if i % 3 == 0 {
            write!(s, "            ").ok();
        }
        write!(s, "({:.9}, {:.9}, {:.9})", p.x, p.y, p.z).ok();
    }
    writeln!(s).ok();
    writeln!(s, "        ]").ok();

    // faceVertexCounts: siempre 3 (triangles)
    writeln!(s, "        int[] faceVertexCounts = [").ok();
    for (i, _) in (0..soup.triangle_count()).enumerate() {
        if i % 20 == 0 && i > 0 {
            writeln!(s).ok();
        } else if i > 0 {
            write!(s, ", ").ok();
        }
        if i % 20 == 0 {
            write!(s, "            ").ok();
        }
        write!(s, "3").ok();
    }
    writeln!(s).ok();
    writeln!(s, "        ]").ok();

    // faceVertexIndices: todos los índices en orden
    writeln!(s, "        int[] faceVertexIndices = [").ok();
    for (i, idx) in soup.indices.iter().enumerate() {
        if i % 20 == 0 && i > 0 {
            writeln!(s).ok();
        } else if i > 0 {
            write!(s, ", ").ok();
        }
        if i % 20 == 0 {
            write!(s, "            ").ok();
        }
        write!(s, "{}", idx).ok();
    }
    writeln!(s).ok();
    writeln!(s, "        ]").ok();

    // Normals si existen
    if !soup.normals.is_empty() {
        writeln!(s, "        normal3f[] normals = [").ok();
        for (i, n) in soup.normals.iter().enumerate() {
            if i % 3 == 0 && i > 0 {
                writeln!(s).ok();
            } else if i > 0 {
                write!(s, ", ").ok();
            }
            if i % 3 == 0 {
                write!(s, "            ").ok();
            }
            write!(s, "({:.9}, {:.9}, {:.9})", n.x, n.y, n.z).ok();
        }
        writeln!(s).ok();
        writeln!(s, "        ] (").ok();
        writeln!(s, "            interpolation = \"vertex\"").ok();
        writeln!(s, "        )").ok();
    }

    writeln!(s, "    }}").ok();
    writeln!(s, "}}").ok();

    Ok(s)
}

#[cfg(test)]
mod tests {
    use super::*;
    use forge_math::DVec3;

    #[test]
    fn usd_contiene_estructura_minima() {
        let s = TriangleSoup {
            name: "cubo".into(),
            positions: vec![
                DVec3::new(0.0, 0.0, 0.0),
                DVec3::new(1.0, 0.0, 0.0),
                DVec3::new(0.0, 1.0, 0.0),
            ],
            indices: vec![0, 1, 2],
            ..Default::default()
        };

        let usda = to_string(&s).unwrap();

        // Estructura
        assert!(usda.contains("#usda 1.0"), "falta header usda");
        assert!(usda.contains("upAxis = \"Z\""), "upAxis no es Z");
        assert!(
            usda.contains("metersPerUnit = 0.001"),
            "metersPerUnit no es 0.001"
        );

        // Malla
        assert!(usda.contains("def Mesh"), "no hay Mesh");
        assert!(usda.contains("def Xform \"stage\""), "no hay stage");
        assert!(usda.contains("point3f[]"), "no hay points");
        assert!(usda.contains("faceVertexCounts"), "no hay faceVertexCounts");
        assert!(
            usda.contains("faceVertexIndices"),
            "no hay faceVertexIndices"
        );

        // Valores
        assert!(usda.contains("0.000000000"), "no contiene vertices");
        assert!(
            usda.contains("1.000000000"),
            "no contiene valores esperados"
        );
    }

    #[test]
    fn usd_rechaza_mallas_invalidas() {
        let mut s = TriangleSoup::default();
        s.positions.clear(); // sin vertices

        assert!(
            to_string(&s).is_err(),
            "deberia rechazar malla sin vertices"
        );
    }

    #[test]
    fn usd_escribe_normales_si_existen() {
        let s = TriangleSoup {
            positions: vec![
                DVec3::new(0.0, 0.0, 0.0),
                DVec3::new(1.0, 0.0, 0.0),
                DVec3::new(0.0, 1.0, 0.0),
            ],
            normals: vec![
                DVec3::new(0.0, 0.0, 1.0),
                DVec3::new(0.0, 0.0, 1.0),
                DVec3::new(0.0, 0.0, 1.0),
            ],
            indices: vec![0, 1, 2],
            ..Default::default()
        };

        let usda = to_string(&s).unwrap();
        assert!(usda.contains("normal3f[]"), "no hay normales");
        assert!(
            usda.contains("interpolation = \"vertex\""),
            "interpolacion incorrecta"
        );
    }
}
