[package]
name = "forge-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Almacen de blobs direccionado por contenido. Columna vertebral de FORGE."

[dependencies]
blake3 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3"
serde_json = { workspace = true }
